# Generated by Django 2.2.3 on 2019-10-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='site_link',
            field=models.URLField(blank=True),
        ),
    ]
