# Generated by Django 2.2.3 on 2019-10-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(blank=True),
        ),
    ]
